language: node_js

node_js:
 - "0.10"
 - "4"
 - "stable"

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

notifications:
  email:
    - dcoates@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - if [ "$TRAVIS_NODE_VERSION" == "0.10" ]; then npm install -g npm@2; fi
  - npm config set spin false

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS fxa'
  - npm i grunt-cli -g
  - npm run outdated
  - grunt nsp --force

script:
  # 'npm run test-travis' runs all tests together to collect all coverage into one from mysql and db-server
  - COVERALLS_REPO_TOKEN=mlOESL8slkePkodJpcvhF1AUKUH3llXi8 npm run test-travis
  # memory tests are separate to avoid being included into coverage because they run through the same code
  - npm run test-mem

matrix:
  allow_failures:
    - node_js: "stable"
  fast_finish: true
