language: node_js

node_js:
 - "8"

dist: trusty

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
  - mysql

notifications:
  email:
    - dcoates@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS fxa'
  - npm i grunt-cli -g
  - npm run outdated
  - grunt nsp --force

script:
  - npm run test-travis
